name: Publish personal site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN_PERSONAL_SITE_2}}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths